# Site
repository: Git repository where your resume will be hosted, only required if you are hosting on GitHub (eg. sproogen/modern-resume-theme)
# favicon: Directory of your favicon (eg. images/favicon.ico)(optional)

# Content configuration version
version: 2

# Personal info
name: 이진서
title: 백엔드 개발자
email: ljjs1215@gmail.com
website: https://jinse0.tistory.com

# Dark Mode (true/false/never)
darkmode: false

# Social links
github_username:  hia0706
facebook_username: ljjs0121@naver.com
# flickr_username: jekyll
instagram_username:
# youtube_username: jekyll

# About Section
# about_title: About Me (Use this to override about section title)
about_profile_image: images/profile.jpg
about_content: | # this will include new lines to allow paragraphs
  Java & Spring 기반의 신입 개발자입니다.


# Projects Section
# projects_title: Projects

# Experience Section
# experience_title: Experience

# Education Section
# educaton_title: Education

# More Section
# 외부 활동
# more_title: A Little More About Me
more_content: | # this will include new lines to allow paragraphs


# Footer
footer_show_references: true
# references_title: References on request (Override references text)

# Build settings
remote_theme: sproogen/modern-resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag

exclude : [
  "Gemfile",
  "Gemfile.lock",
  "node_modules",
  "vendor/bundle/",
  "vendor/cache/",
  "vendor/gems/",
  "vendor/ruby/",
  "lib/",
  "scripts/",
  "docker-compose.yml",
  ]
